### ISSUE TITLE
Can not find utils

### ISSUE THREAD

**Issue by hattorihanzo76** [conficient/versionReaderTask#12]
I'm not sure if it's caused by Version 2.3 but actually I get the following error:

2021-03-14T15:32:10.8845847Z ##[section]Starting: Generate variables /home/vsts/work/r1/a/_MT.DataAccess.Abstract/MT.DataAccess.Abstract.csproj 
2021-03-14T15:32:10.9109525Z ==============================================================================
2021-03-14T15:32:10.9110554Z Task         : Version Reader
2021-03-14T15:32:10.9111278Z Description  : Reads the <Version> tag value project file and makes it available as build variables. V2 now rewritten in TypeScript and is cross-platform
2021-03-14T15:32:10.9111711Z Version      : 2.3.0
2021-03-14T15:32:10.9112223Z Author       : Conficient
2021-03-14T15:32:10.9113325Z Help         : 
2021-03-14T15:32:10.9113625Z ==============================================================================
**2021-03-14T15:32:11.4624444Z ##[error]Unhandled: Cannot find module './utils'**
2021-03-14T15:32:11.4703605Z ##[section]Finishing: Generate variables /home/vsts/work/r1/a/_MT.DataAccess.Abstract/MT.DataAccess.Abstract.csproj

**Comment by chriszuercher** [comment]
I face the same issue using Version 2.3.0 since today. It was working fine on Friday using version 2.2.0. Is there anything broken in 2.3? And is there any way to use the former version so be can cotinure working?

**Comment by mbho** [comment]
I also have this problem, it only occurs on Linux machines, when I switch to Windows VMs it still works.

**Comment by conficient** [comment]
Yeah sorry about that - I had to update due to a security patch in the xmldom library - something obviously didn't work correctly in the upgrade. I'll fix and push a new version.

**Comment by conficient** [comment]
OK am reversing the changes but upgrading the version to v2.4 - that should work. I think the issue was that the `Utils.ts` file was upper case on my machine, but when TypeScript compiled it imports `'utils'` and that's not getting found on Linux builds. Not sure how that worked before but I've fixed now. Will leave this issue open until I've got a working Linux build (it's broken for me too!)

**Comment by mbho** [comment]
Thank you for the quick response. Version 2.4 is working in my environment, thanks!

**Comment by conficient** [comment]
Thanks for the confirmation -- will close
